spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名和下划线命名的自动转换  (获取用户时间)