spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8
    username: root
    password: root